# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-PostgreSQL
    orgId: 1

datasources:
  - name: CarConnectivity-PostgreSQL
    orgId: 1
    uid: CarConnectivity-PostgreSQL-provisioned
    type: postgres
    access: proxy
    user: $DB_USER
    secureJsonData:
      password: $DB_PASSWORD
    jsonData:
      database: $DB_NAME
      sslmode: "disable"
      postgresVersion: 1500
    url: $DB_HOSTNAME:$DB_PORT
    basicAuth: false
    withCredentials: false
    isDefault: true
    editable: false