# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-SQLite
    orgId: 1

datasources:
  - name: CarConnectivity-SQLite
    orgId: 1
    uid: CarConnectivity-SQLite-provisioned
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /home/grafana/.carconnectivity/carconnectivity.db
    url: $DB_HOSTNAME:$DB_PORT
    isDefault: false
    editable: false