# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-SQLite
    orgId: 1

datasources:
  - name: CarConnectivity-SQLite
    orgId: 1
    uid: P2EF847825A020B66
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /home/grafana/.carconnectivity/carconnectivity.db
    isDefault: true
    editable: false