# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-ENV-json
    orgId: 1

datasources:
  - name: CarConnectivity-ENV-json
    orgId: 1
    uid: CarConnectivity-Env-json-provisioned
    type: marcusolsson-json-datasource
    access: proxy
    url: http://localhost:8081/env.json
    basicAuthUser: grafana
    secureJsonData:
      basicAuthPassword: grafanasecretaccesshttpd
    jsonData:
      timeout: "1"
    basicAuth: true
    isDefault: false
    editable: false
    
