# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-live-json
    orgId: 1

datasources:
  - name: CarConnectivity-live-json
    orgId: 1
    uid: CarConnectivity-live-json-provisioned
    type: yesoreyeram-infinity-datasource
    url: ${CARCONNECTIVITY_UI_URL}/garage/json
    basicAuth: true
    basicAuthUser: $CARCONNECTIVITY_USERNAME
    jsonData:
      auth_method: 'basicAuth'
      allowedHosts:
      - '${CARCONNECTIVITY_UI_URL}'
      oauthPassThru: false
      tlsSkipVerify: true
      timeoutInSeconds: 5
      allowDangerousHTTPMethods: false
    secureJsonData:
      basicAuthPassword: $CARCONNECTIVITY_PASSWORD
    isDefault: false
    editable: false